import type { AppProps } from 'next/app';
import React from 'react';
import AppContainer from '@/app-container';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <AppContainer>
      <Head>
        <title>Bamitex</title>
        <meta name="description" content="Generated by Bamitex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </AppContainer>
  );
}
