import List from '@/components/common/list';
import Head from 'next/head';
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bamitex</title>
        <meta name="description" content="Generated by Bamitex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h4>داشبورد</h4>
      <List>
        {[
          {
            body: <div>body</div>,
            id: 'bitcoin'
          },
          {
            body: <div>body</div>,
            id: 'binance coin'
          },
          {
            body: <div>body</div>,
            id: 'ethereum'
          },
          {
            body: <div>body</div>,
            id: 'solana'
          },
          {
            body: <div>body</div>,
            id: 'usdt'
          },
          {
            body: <div>+ مدیریت لیست کوین ها</div>,
            id: 'manage tokens'
          },
        ]}
      </List>
    </>
  );
}
